
kind: pipeline
name: default

clone:
  disable: true

workspace:
  path: /app/src

volumes:
- name: cache
  temp:
    medium: memory

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/DangerousThings/flexsecure-applets .
  - git -c submodule."smartcard-ci".update=none -c submodule."applets/apex-fido2".update=none -c submodule."applets/apex-tesla".update=none -c submodule."applets/apex-ndef".update=none -c submodule."applets/apex-spark".update=none submodule update --init --recursive
- name: build  
  image: stargate01/smartcard-ci
  commands:
  - /app/src/scripts/compile-all.sh
  volumes:
  - name: cache
    path: /tmp
- name: test  
  image: stargate01/smartcard-ci
  commands:
  - /app/src/scripts/test-all.sh
  volumes:
  - name: cache
    path: /tmp
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api_key
    files: /app/src/bin/*
  when:
    branch:
    - master
    event:
    - tag
